results_dir: '/workspace/tao-experiments/classification_tf2/byom_person/results_resnet18/output'
encryption_key: 'nvidia_tlt'
dataset:
  train_dataset_path: "/workspace/tao-experiments/data/split/train"
  val_dataset_path: "/workspace/tao-experiments/data/split/val"
  preprocess_mode: 'tf'
  num_classes: 2
  augmentation:
    enable_color_augmentation: True
    enable_center_crop: False
    enable_random_crop: True
    mixup_alpha: 0.2
train:
  qat: False
  checkpoint: ''
  batch_size_per_gpu: 64
  num_epochs: 120
  optim_config:
    optimizer: 'adam'
  lr_config:
    scheduler: 'cosine'
    learning_rate: 0.001
    soft_start: 0.05
  reg_config:
    type: 'L2'
    scope: ['conv2d', 'dense']
    weight_decay: 0.00005
model:
  backbone: 'byom'
  input_width: 128
  input_height: 128
  input_channels: 3
  input_image_depth: 8
  byom_model: '/workspace/tao-experiments/classification_tf2/pretrained_resnet18/resnet18_128/resnet18_128.tltb'
  resize_interpolation_method: 'bilinear'
  use_batch_norm: True
  freeze_bn: False
  freeze_blocks: [0,3]
evaluate:
  dataset_path: "/workspace/tao-experiments/data/split/test"
  checkpoint: "EVALMODEL"
  top_k: 1
  batch_size: 64
  n_workers: 8
prune:
  byom_model_path: '/workspace/tao-experiments/classification_tf2/pretrained_resnet18/resnet18_128/resnet18_128.tltb'
  checkpoint: 'EVALMODEL'
  threshold: 0.68
  min_num_filters: 8
